


# format: 
# https://files.tofugu.com/articles/japanese/2014-06-30-learn-hiragana/%E3%81%82.mp3

import requests
import os.path


def getAudioData(character = "あ"):
    # if character in "（）":
    #     # skip because its just a parenthesis
    #     return None

    # url = f"https://cdn.jsdelivr.net/npm/hanzi-writer-data@latest/{character}.json"

    url = f"https://files.tofugu.com/articles/japanese/2014-06-30-learn-hiragana/{character}.mp3"
    response = requests.get(url)
    audio = response.content
    # audio = jsonData.decode()

    # print(response.content)
    # error: Error: Redirecting...
    # if "Couldn't find the requested file" in jsonData:
    if "Error: Redirecting..." in str(audio):
        print("could not find file for '" + character + "'; skipping this character")
        return
    
    
    path = f'hiraganaAudio/{character}.mp3'
    check_file = os.path.isfile(path)

    if check_file:
        print(f"{character}.mp3 already exists; skipping")
        return

    print(f"downloading {character}.mp3")



    # download by writing to a file
    filename = f"hiraganaAudio/{character}.mp3"
    with open(filename, 'wb') as f:
        f.write(audio)


# generated by gemini
allHiragana = \
"""
あいうえお
さしすせそ
たちつてと
なにはの
かきくけこ
ひふへほ
まみむめも
やゆよ
らりるれろ
わをん
"""

allHiragana = "ねぬ" + allHiragana

for x in allHiragana: 
    getAudioData(x)
    

getAudioData('あ')
